// Dependencies
import { LuarmorClient } from "./index.js";

// Vars
const apiKey = ""
const projectId = ""

// Create the client
let Client = new LuarmorClient(apiKey)
console.log("Successfully initialised the client")

// Grabbing stats
console.log("API status:")
console.log(await Client.status())

// Grabbing key details
console.log("Key details:")
const keyDetails = await Client.keyDetails()
console.log(keyDetails)
console.log(keyDetails.projects?.[0])

// Grabbing key stats
console.log("Key stats:")
console.log(await Client.keyStats())

// Get users
console.log("Get users:")
console.log((await Client.getUsers(projectId)).message)

// Create a key
const createdKey = await Client.createKey(projectId, {
    note: "TEST KEY - generated by luarmor-ts",
})
const testKey = createdKey.user_key || ""
console.log("Key Creation:")
console.log(createdKey)

// Update the key
console.log("Update Key:")
console.log(await Client.updateUser(projectId, {
    user_key: testKey
}))

// Force reset HWID
console.log("Reset HWID:")
console.log(await Client.resetHWID(projectId, {
    user_key: testKey,
    force: true
}))

// Link Discord ID
console.log("Link Discord ID:")
console.log(await Client.linkDiscord(projectId, {
    user_key: testKey,
    discord_id: "1234578635849",
    force: true
}))

// Delete the key
console.log("Key deletion:")
console.log(await Client.deleteKey(projectId, testKey))